FROM jenkins/jenkins:lts-jdk17

USER root

# Instalar plugins necesarios (SOLO los esenciales)
RUN jenkins-plugin-cli --plugins \
    git \
    workflow-aggregator \
    maven-plugin \
    docker-workflow

# Instalar herramientas
RUN apt-get update && \
    apt-get install -y \
    maven \
    docker.io \
    git \
    && rm -rf /var/lib/apt/lists/*

USER jenkins